import type { Book, Loan, Reservation, LibraryStats, Notification, FineRecord, LibraryUser } from "./types";

export const mockUsers: LibraryUser[] = [
  {
    id: "admin-1",
    email: "admin@library.ug",
    name: "Sarah Nakamya",
    role: "admin",
    phone: "+256 750 492418",
    membershipDate: "2023-01-15",
    membershipId: "ADM-001",
    status: "active",
  },
  {
    id: "member-1",
    email: "member@library.ug",
    name: "Joseph Ssemakula",
    role: "member",
    phone: "+256 770 123456",
    membershipDate: "2024-06-10",
    membershipId: "MEM-1042",
    status: "active",
  },
];

const coverPlaceholders = [
  "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=400&fit=crop",
];

export const mockBooks: Book[] = [
  {
    id: "book-1",
    title: "Introduction to Physics",
    author: "Dr. James Mukasa",
    isbn: "978-0-13-468599-1",
    coverUrl: coverPlaceholders[0],
    description: "A comprehensive introduction to physics for secondary school students in Uganda, covering mechanics, thermodynamics, and modern physics.",
    category: "Science",
    format: "physical",
    status: "available",
    totalCopies: 15,
    availableCopies: 8,
    publishedYear: 2023,
    publisher: "East African Publishers",
    pages: 420,
    language: "English",
    barcode: "LIB-PHY-001",
    addedDate: "2024-01-15",
    rating: 4.5,
    borrowCount: 142,
  },
  {
    id: "book-2",
    title: "Mathematics for O-Level",
    author: "Prof. Agnes Namutebi",
    isbn: "978-0-07-352332-7",
    coverUrl: coverPlaceholders[1],
    description: "Complete mathematics textbook aligned with the Uganda National Examinations Board syllabus for O-Level.",
    category: "Mathematics",
    format: "physical",
    status: "available",
    totalCopies: 20,
    availableCopies: 3,
    publishedYear: 2024,
    publisher: "Fountain Publishers",
    pages: 560,
    language: "English",
    barcode: "LIB-MAT-001",
    addedDate: "2024-03-20",
    rating: 4.8,
    borrowCount: 210,
  },
  {
    id: "book-3",
    title: "African Literature Anthology",
    author: "Chinua Achebe et al.",
    isbn: "978-0-435-91200-3",
    coverUrl: coverPlaceholders[2],
    description: "A curated collection of the finest African literary works spanning poetry, prose, and drama from across the continent.",
    category: "Literature",
    format: "digital",
    status: "available",
    totalCopies: 1,
    availableCopies: 1,
    publishedYear: 2022,
    publisher: "Heinemann",
    pages: 380,
    language: "English",
    digitalUrl: "/ebooks/african-lit.pdf",
    digitalFormat: "pdf",
    addedDate: "2024-02-10",
    rating: 4.7,
    borrowCount: 89,
  },
  {
    id: "book-4",
    title: "History of East Africa",
    author: "Dr. Peter Odhiambo",
    isbn: "978-9-966-25000-1",
    coverUrl: coverPlaceholders[3],
    description: "Detailed historical account of East African civilizations, colonial era, and the path to independence.",
    category: "History",
    format: "physical",
    status: "borrowed",
    totalCopies: 10,
    availableCopies: 0,
    publishedYear: 2021,
    publisher: "Longhorn Publishers",
    pages: 340,
    language: "English",
    barcode: "LIB-HIS-001",
    addedDate: "2023-09-05",
    rating: 4.3,
    borrowCount: 167,
  },
  {
    id: "book-5",
    title: "Biology: A Ugandan Perspective",
    author: "Dr. Florence Amuge",
    isbn: "978-9-970-02500-5",
    coverUrl: coverPlaceholders[4],
    description: "Biology textbook featuring local ecosystems, tropical diseases, and conservation efforts in Uganda.",
    category: "Science",
    format: "physical",
    status: "available",
    totalCopies: 12,
    availableCopies: 5,
    publishedYear: 2024,
    publisher: "MK Publishers",
    pages: 490,
    language: "English",
    barcode: "LIB-BIO-001",
    addedDate: "2024-05-12",
    rating: 4.6,
    borrowCount: 95,
  },
  {
    id: "book-6",
    title: "Luganda Grammar & Composition",
    author: "Prof. Ssemakula Kiwanuka",
    isbn: "978-9-970-03100-6",
    coverUrl: coverPlaceholders[5],
    description: "Comprehensive guide to Luganda language grammar, composition, and oral literature for secondary students.",
    category: "Languages",
    format: "digital",
    status: "available",
    totalCopies: 1,
    availableCopies: 1,
    publishedYear: 2023,
    publisher: "Fountain Publishers",
    pages: 280,
    language: "Luganda/English",
    digitalUrl: "/ebooks/luganda-grammar.pdf",
    digitalFormat: "pdf",
    addedDate: "2024-04-01",
    rating: 4.2,
    borrowCount: 56,
  },
  {
    id: "book-7",
    title: "Chemistry Practical Handbook",
    author: "Dr. Moses Kiggundu",
    isbn: "978-0-19-914850-7",
    coverUrl: coverPlaceholders[6],
    description: "Step-by-step laboratory manual for chemistry practicals aligned with UNEB requirements.",
    category: "Science",
    format: "physical",
    status: "available",
    totalCopies: 8,
    availableCopies: 6,
    publishedYear: 2024,
    publisher: "Oxford University Press",
    pages: 220,
    language: "English",
    barcode: "LIB-CHM-001",
    addedDate: "2024-06-18",
    rating: 4.4,
    borrowCount: 78,
  },
  {
    id: "book-8",
    title: "Entrepreneurship & Business Studies",
    author: "Grace Achieng",
    isbn: "978-9-970-04200-8",
    coverUrl: coverPlaceholders[7],
    description: "Practical guide to entrepreneurship with case studies from Ugandan businesses and startups.",
    category: "Business",
    format: "digital",
    status: "available",
    totalCopies: 1,
    availableCopies: 1,
    publishedYear: 2025,
    publisher: "East African Publishers",
    pages: 310,
    language: "English",
    digitalUrl: "/ebooks/entrepreneurship.epub",
    digitalFormat: "epub",
    addedDate: "2025-01-10",
    rating: 4.9,
    borrowCount: 34,
  },
  {
    id: "book-9",
    title: "Computer Science Fundamentals",
    author: "Dr. Ivan Mugisha",
    isbn: "978-1-292-15906-9",
    coverUrl: coverPlaceholders[0],
    description: "Introduction to programming, algorithms, and data structures for A-Level computer science students.",
    category: "Technology",
    format: "physical",
    status: "available",
    totalCopies: 6,
    availableCopies: 4,
    publishedYear: 2024,
    publisher: "Pearson",
    pages: 450,
    language: "English",
    barcode: "LIB-CS-001",
    addedDate: "2024-08-22",
    rating: 4.7,
    borrowCount: 62,
  },
  {
    id: "book-10",
    title: "Islamic Studies for Secondary Schools",
    author: "Sheikh Abdul Karim",
    isbn: "978-9-970-05300-9",
    coverUrl: coverPlaceholders[1],
    description: "Comprehensive Islamic studies textbook covering Quran, Hadith, Fiqh, and Islamic history.",
    category: "Religious Studies",
    format: "physical",
    status: "available",
    totalCopies: 18,
    availableCopies: 12,
    publishedYear: 2023,
    publisher: "Islamic University Press",
    pages: 360,
    language: "English/Arabic",
    barcode: "LIB-ISL-001",
    addedDate: "2023-11-30",
    rating: 4.8,
    borrowCount: 185,
  },
  {
    id: "book-11",
    title: "Geography of Uganda & East Africa",
    author: "Dr. Harriet Nambi",
    isbn: "978-9-966-25100-2",
    coverUrl: coverPlaceholders[2],
    description: "Physical and human geography of Uganda and the East African region with maps and case studies.",
    category: "Geography",
    format: "physical",
    status: "reserved",
    totalCopies: 10,
    availableCopies: 2,
    publishedYear: 2024,
    publisher: "Longhorn Publishers",
    pages: 400,
    language: "English",
    barcode: "LIB-GEO-001",
    addedDate: "2024-07-14",
    rating: 4.1,
    borrowCount: 73,
  },
  {
    id: "book-12",
    title: "The Pearl of Africa: Stories",
    author: "Jennifer Nansubuga Makumbi",
    isbn: "978-1-78607-400-3",
    coverUrl: coverPlaceholders[3],
    description: "Award-winning collection of short stories set in Uganda, exploring culture, identity, and modern life.",
    category: "Literature",
    format: "digital",
    status: "available",
    totalCopies: 1,
    availableCopies: 1,
    publishedYear: 2025,
    publisher: "Oneworld Publications",
    pages: 260,
    language: "English",
    digitalUrl: "/ebooks/pearl-of-africa.epub",
    digitalFormat: "epub",
    addedDate: "2025-02-01",
    rating: 4.9,
    borrowCount: 28,
  },
];

export const mockLoans: Loan[] = [
  {
    id: "loan-1",
    bookId: "book-4",
    book: mockBooks[3],
    memberId: "member-1",
    memberName: "Joseph Ssemakula",
    issueDate: "2026-02-10",
    dueDate: "2026-02-24",
    status: "active",
    renewCount: 0,
    fine: 0,
  },
  {
    id: "loan-2",
    bookId: "book-2",
    book: mockBooks[1],
    memberId: "member-1",
    memberName: "Joseph Ssemakula",
    issueDate: "2026-02-01",
    dueDate: "2026-02-15",
    status: "overdue",
    renewCount: 1,
    fine: 5000,
  },
  {
    id: "loan-3",
    bookId: "book-1",
    book: mockBooks[0],
    memberId: "member-2",
    memberName: "Amina Nabirye",
    issueDate: "2026-02-20",
    dueDate: "2026-03-06",
    status: "active",
    renewCount: 0,
    fine: 0,
  },
  {
    id: "loan-4",
    bookId: "book-5",
    book: mockBooks[4],
    memberId: "member-3",
    memberName: "David Ochieng",
    issueDate: "2026-01-28",
    dueDate: "2026-02-11",
    status: "overdue",
    renewCount: 0,
    fine: 7500,
  },
  {
    id: "loan-5",
    bookId: "book-9",
    book: mockBooks[8],
    memberId: "member-1",
    memberName: "Joseph Ssemakula",
    issueDate: "2026-02-22",
    dueDate: "2026-03-08",
    status: "active",
    renewCount: 0,
    fine: 0,
  },
];

export const mockReservations: Reservation[] = [
  {
    id: "res-1",
    bookId: "book-4",
    book: mockBooks[3],
    memberId: "member-2",
    memberName: "Amina Nabirye",
    reservedDate: "2026-02-24",
    status: "pending",
  },
  {
    id: "res-2",
    bookId: "book-11",
    book: mockBooks[10],
    memberId: "member-1",
    memberName: "Joseph Ssemakula",
    reservedDate: "2026-02-25",
    status: "ready",
  },
];

export const mockStats: LibraryStats = {
  totalPhysicalBooks: 12450,
  totalEbooks: 5230,
  totalMembers: 1847,
  activeLoans: 342,
  overdueBooks: 23,
  newMemberRequests: 8,
  todayReturns: 15,
  todayIssues: 22,
};

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "overdue",
    title: "5 Books Overdue Today",
    message: "There are 5 books that became overdue today. Please follow up with the members.",
    timestamp: "2026-02-26T08:00:00Z",
    read: false,
  },
  {
    id: "notif-2",
    type: "membership",
    title: "New Membership Request",
    message: "Amina Nabirye has requested a library membership. Review and approve.",
    timestamp: "2026-02-26T07:30:00Z",
    read: false,
  },
  {
    id: "notif-3",
    type: "reservation",
    title: "Book Ready for Collection",
    message: "'History of East Africa' is now available for Joseph Ssemakula's reservation.",
    timestamp: "2026-02-25T16:00:00Z",
    read: true,
  },
  {
    id: "notif-4",
    type: "return",
    title: "Book Returned",
    message: "David Ochieng returned 'Biology: A Ugandan Perspective' with a fine of UGX 7,500.",
    timestamp: "2026-02-25T14:20:00Z",
    read: true,
  },
  {
    id: "notif-5",
    type: "system",
    title: "System Maintenance",
    message: "Scheduled maintenance on March 1st from 2:00 AM to 4:00 AM EAT.",
    timestamp: "2026-02-24T10:00:00Z",
    read: true,
  },
];

export const mockFines: FineRecord[] = [
  {
    id: "fine-1",
    loanId: "loan-2",
    bookTitle: "Mathematics for O-Level",
    amount: 5000,
    reason: "Overdue by 11 days",
    status: "unpaid",
    createdDate: "2026-02-15",
  },
  {
    id: "fine-2",
    loanId: "loan-old-1",
    bookTitle: "Introduction to Physics",
    amount: 2000,
    reason: "Overdue by 4 days",
    status: "paid",
    createdDate: "2026-01-20",
    paidDate: "2026-01-25",
  },
];

export const bookCategories = [
  "All",
  "Science",
  "Mathematics",
  "Literature",
  "History",
  "Languages",
  "Business",
  "Technology",
  "Religious Studies",
  "Geography",
  "Arts",
];
